
# Site settings
title: ishotjr.github.io
# email: your-email@domain.com
description: #TODO >
baseurl: ""		# no trailing slash
url: "http://ishotjr.github.io"	# no trailing slash
twitter_username: IShJR
github_username:  ishotjr

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
- jemoji
